Repository timerring/DanmakuConvert, pull requests merged in 2025-03, with the labels that each got.

#1 feat: add gift add guard
  danmaku_convert.py
  sample.xml
Labels: good first issue

#3 feat: add superchat animation
  danmaku_convert.py
  superchat.py
Labels: enhancement

#6 feat: add cli usage
  danmaku_convert.py
  dmconvert/__init__.py
  dmconvert/cli.py
  dmconvert/convert.py
  dmconvert/guardgift/__init__.py
  dmconvert/guardgift/gg_handler.py
  dmconvert/guardgift/guard_and_gift.py
  dmconvert/header/__init__.py
  dmconvert/header/header.py
  dmconvert/normal/__init__.py
  dmconvert/normal/danmaku_array.py
  dmconvert/normal/normal_handler.py
  dmconvert/superchat/__init__.py
  dmconvert/superchat/superchat.py
  dmconvert/superchat/superchat_handler.py
  dmconvert/utils.py
Labels: feature

#7 fix: adapted to the resolution
  dmconvert/convert.py
  dmconvert/superchat/superchat_handler.py
Labels: enhancement

#8 feat: remove abundant emojis
  dmconvert/normal/normal_handler.py
  dmconvert/utils.py
  sample.xml
Labels: enhancement

#9 refactor: adjust structure
  dmconvert/guardgift/gg_handler.py
  dmconvert/guardgift/guard_and_gift.py
Labels: enhancement

#10 refactor: adjust text lines
  dmconvert/superchat/superchat_handler.py
Labels: enhancement

#13 docs: update readme
  .gitignore
  README.md
Labels: documentation

#15 build: release package
  pyproject.toml
Labels: enhancement

#17 docs: update icon
  README-zh.md
  README.md
  assets/headerDark.svg
  assets/headerLight.svg
Labels: documentation

#18 docs: update icon
  README-zh.md
  README.md
  assets/headerDark.svg
  assets/headerLight.svg
Labels: documentation

#19 fix: fix overlap issues
  dmconvert/normal/danmaku_array.py
  dmconvert/normal/normal_handler.py
Labels: bug

#20 fix: refactor text length function
  dmconvert/convert.py
  dmconvert/normal/normal_handler.py
  dmconvert/utils.py
Labels: enhancement

#21 docs: update superchat rules
  README-en.md
  README.md
Labels: documentation

#23 build: release 0.0.2
  README-en.md
  README.md
  dmconvert/cli.py
  dmconvert/convert.py
  dmconvert/normal/normal_handler.py
  dmconvert/superchat/superchat_handler.py
  pyproject.toml
Labels: enhancement

#24 style: adjust superchat style
  dmconvert/superchat/superchat.py
Labels: enhancement

#26 feat: resize according to resolution
  dmconvert/header/header.py
  dmconvert/superchat/superchat.py
  dmconvert/superchat/superchat_handler.py
Labels: feature

#27 feat: superchat fontsize
  README-en.md
  README.md
  dmconvert/cli.py
  dmconvert/convert.py
  dmconvert/guardgift/gg_handler.py
  dmconvert/header/header.py
  dmconvert/superchat/superchat_handler.py
Labels: feature

#28 build: release 0.0.3
  dmconvert/cli.py
  dmconvert/convert.py
  pyproject.toml
Labels: enhancement

#29 refactor: change to relative import
  dmconvert/__init__.py
  dmconvert/convert.py
Labels: enhancement

#30 feat: add douyin danmaku test
  dmconvert/normal/dytest.py
Labels: feature

#31 feat: add animation of move & add read_xml_file function
  dmconvert/normal/dytest.py
Labels: feature

#32 fix: superchat range issue
  dmconvert/superchat/superchat.py
Labels: enhancement

#34 fix: BTM render issue
  dmconvert/normal/normal_handler.py
Labels: enhancement
